### ISSUE TITLE
Music stops playing after a few seconds

### ISSUE THREAD

**Issue by GameplaysRFun** [TeamCernodile/Freezy#21]
Freezy leaves VC after playing the song a few seconds, and then replies "No new songs have been requested in time. Leaving voice channel!"

**Comment by cernodile** [comment]
Need more context, logs, installed modules, have ffmpeg or libav or anything, have build-tools, etc.

**Comment by GameplaysRFun** [comment]
Sorry, must specify. It was your bot.

**Comment by cernodile** [comment]
I can't do much without knowing exactly when, how to repro, etc.
